### ISSUE TITLE
setup.py pulls incompatible networkx v 2 if v1x is not already installed

### ISSUE THREAD

**Issue by lschilli** [SocialCognitiveSystems/PRIMO#20]
networkx version 2 is pulled by setup.py if networkx is not already installed on the system.
primo does not work with this version.

**Comment by jpoeppel** [comment]
Thanks a for reporting. We'll have to see if want to transition to the new version, or just freece the dependency to v1. We also considered dropping the requirement at some point since we do not use it for all  that much.

**Comment by jpoeppel** [comment]
Currently the patch in #23 uses the fact that networkx 2 still exposed Graph.node as a shortcut to Graph.nodes. 
In their release notes they hint at removing this alias in networkx 3.x in the future so I thought about also monkey patching this (since I already monkey patch the use of iterators in networkx 1.x), however this is not that trivial as the current code uses "Graph.nodes" already to access the iterator over all nodes. If I were to monkey patch Graph.nodes to Graph.node for networkx 1.x in order to access specific nodes (as in Graph.nodes["a"]), I would overwrite the already existing patch for the iterator. In networkx 2.0 this name ambiguity is not a problem, since nodes does not return a plain iterator/dictionary, but a "NodeView" which can act as both a list/iterator and a dictionary depending on its use.
